name: laravel
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    


jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:

    - name: Get latest code
      uses: actions/checkout@master

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: EXCLUDED_FOR_SECURITY
        local-dir: "./public_html/testLaravelGitDeploy/"
        server-dir: "/home/codeitc/public_html/testLaravelGitDeploy"
        username: ${{ secrets.PROD_FTP_USER }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        state-name: sync-state.json