name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
 deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
