name: laravel
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Upload from public_html via FTP
#         uses: airvzxf/ftp-deployment-action@latest
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           user: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local_dir: "./public_html/testLaravelGitDeploy/"
#           remote_dir: "/home/codeitc/public_html/testLaravelGitDeploy"
#           delete: "true"
#           max_retries: "7"
#           no_symlinks: "false"
#           ftp_ssl_allow: "true"
#           ftp_use_feat: "true"
#           ftp_nop_interval: "9"
#           net_max_retries: "0"
#           net_persist_retries: "11"
#           net_timeout: "13s"
#           dns_max_retries: "17"
#           dns_fatal_timeout: "never"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Eleventy
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output html
          install_dependencies: true

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "/home/codeitc/public_html/testLaravelGitDeploy"
          target: "${{ secrets.REMOTE_DIR }}"
