name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploye app
      uses: actions/checkout@v2

      - name: Sync files
        user: SamKirKland/FTP-Deploy-Action@4.0.0
        with:
          server: 59.144.165.144
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: 'cd home/codeitc/public_html/testLaravelGitDeploy/  && ./deployer.sh'
